apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seconddeploy
  name: seconddeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seconddeploy
  strategy: {}
  template:
    metadata:
      labels:
        app: seconddeploy
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
