apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-rolling
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%   # Güncelleme sırasında en fazla %25 pod devre dışı kalabilir
      #maxSurge: 25%         # Güncelleme sırasında en fazla %25 yeni pod eklenebilir
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.26
        ports:
        - containerPort: 80

        