apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskpv
  name: volumesvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: taskpv
  type: NodePort
status:
  loadBalancer: {}
