apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretcm-deploy
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secretcm
  template:
    metadata:
      labels:
        app: secretcm
    spec:
      containers:
      - name: secretcm-container
        image: ahmetcan2022/secretcmtest:latest
        ports:
        - containerPort: 5000
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: secretcm-config
              key: WELCOME_MESSAGE
        - name: APP_USER
          valueFrom:
            secretKeyRef:
              name: secretcm-secret
              key: APP_USER
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretcm-secret
              key: APP_PASSWORD