apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas:   1  # Canary için çok sayıda
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ahmetcan2022/myapp:v2
        ports:
        - containerPort: 80