apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas:   3 # Canary için çok sayıda
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: httpd
        ports:
        - containerPort: 80