apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: blue    # 👈 Trafiği BLUE deployment’a yönlendiriyor
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort