apiVersion: apps/v1  # StatefulSet API sürümü
kind: StatefulSet     # Kaynağın tipi StatefulSet
metadata:
  name: simple-web    # StatefulSet ismi
spec:
  serviceName: "simple-web"  # StatefulSet için headless service ismi (pod discovery için)
  replicas: 3               # Oluşturulacak pod sayısı
  selector:
    matchLabels:
      app: simple-web      # StatefulSet'in hangi podları yöneteceğini seçer
  template:
    metadata:
      labels:
        app: simple-web    # Podlara atanacak label, selector ile eşleşmeli
    spec:
      containers:
      - name: nginx         # Container adı
        image: nginx:stable # Container imajı
        ports:
        - containerPort: 80 # Container içindeki port
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html  # Container içinde PVC’nin bağlanacağı yol
  volumeClaimTemplates:      # Her pod için otomatik PVC oluşturma şablonu
  - metadata:
      name: www             # PVC ismi
    spec:
      accessModes: ["ReadWriteOnce"]  # PVC erişim modu, sadece tek node üzerinden yazabilir
      resources:
        requests:
          storage: 1Mi     # Her PVC için ayrılacak minimum storage miktarı