apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
    - name: secret
      image: nginx
      env:
        - name: USER                                  
          valueFrom:
            secretKeyRef:
              name: mysecret          
              key: USER 
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASS

 # kubectl create secret generic mysecret --from-literal=USER=admin --from-literal=PASS=123
        