apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    env:
    - name: USER
      valueFrom:
        configMapKeyRef:
          name: mycm
          key: USER
    - name: PASS
      valueFrom:
        configMapKeyRef:
          name: mycm
          key: PASS  

#CM yapısını env üzerinden görebiliriz 
    

  