apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodedeploy
  name: deploysvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: nodedeploy
  type: NodePort
status:
  loadBalancer: {}
